### ISSUE TITLE
Trigger on channel event

### ISSUE THREAD

**Issue by ds82** [lewie/openhab2-javascript#1]
Is it possible to create a trigger that set off on a channel event?

I tried to add a helper function to generates a channel trigger, but something seems wrong:

```
function channelTrigger(channel, event, triggerName) {
  return new Trigger(triggerName || uuid.randomUUID(), "core.ChannelEventTrigger", new Configuration({
      "eventSource": channel,
      "eventTopic":"smarthome/channels/" + event + "/triggered",
      "eventTypes":"ChannelTriggeredEvent"
  }));
}
```

hmm .. found another forums post and also tried this:

```
function channelTrigger(channel, event, triggerName) {
  return new Trigger(triggerName || uuid.randomUUID(), "core.ChannelEventTrigger", new Configuration({
    channelUID: channel,
    event: event
  }));
}
```

**Comment by ds82** [comment]
Ok, the latter worked ... used it like that:

```
channelTrigger('astro:sun:home:rise#event', 'START')
```

many thanks for this repo! :)

**Comment by lewie** [comment]
👍 Just moved around yet to find a solution.... Yours is best! :-)

I think most helping people could be found on 
[community.openhab.org](https://community.openhab.org/search?q=jsr223%20javascript)

**Comment by lewie** [comment]
@ds82, I have extended and updated some classes: [ChannelEventTrigger](https://github.com/lewie/openhab2-javascript/blob/master/jslib/triggersAndConditions.js#L75) should do what you need now.
