### ISSUE TITLE
Avoid hard coding path to libraries

### ISSUE THREAD

**Issue by rkoshak** [lewie/openhab2-javascript#2]
Is there a way to avoid hard coding the path to the libraries in the scripts? Maybe have something defined in one place that all the rest of the scripts load?

The problem is when running in Docker or in a manually installed OH the automation folder will not be in /etc/openhab2.

As a heads up, given the status of the ERE and the fact that PaperUI Rules only supports JavaScript at the moment, I expect this library to start getting a lot more attention. I intend to write the docs for the Next-Gen Rules Engine to reference this library heavily. Thanks for posting it!

**Comment by lewie** [comment]
Haha, it took me a little... we can use:

```
var OPENHAB_CONF = load(Java.type("java.lang.System").getenv("OPENHAB_CONF"));
load(OPENHAB_CONF+'/automation/jsr223/jslib/JSRule.js');
```
or simply
```
load(Java.type("java.lang.System").getenv("OPENHAB_CONF")+'/automation/jsr223/jslib/JSRule.js'));
```

I've read your great contribution before, good idea! https://community.openhab.org/t/working-with-paperui-rules-experiments/54669

There are many updates, corrections and ideas for this. I also believe that it is time to document these many topics! I hope, I can spend some time at the weekend.
